### ISSUE TITLE
any reason why no subProperty entailment?

### ISSUE THREAD

**Issue by doriantaylor** [ruby-rdf/rdf-reasoner#4]
Is there a strategic reason why a `subProperty` entailment (the inverse of `subPropertyOf`, an analogue to `subClass`) was left out of this package? At any rate, I just hacked one in. Shall I patch?

**Comment by gkellogg** [comment]
I don't recall, but it does seem odd that it was left out. If you'd like to add `subProperty` along with `_entail_subProperty` and tests, that would be great.

Note that there are a number of other entailments missing, as trying to run spec/suite_spec.rb will detail.

**Comment by doriantaylor** [comment]
cool; I just copied `subClass`, `_entail_subClass` etc. Seems to be enough. Coming up…
